format = """
$directory$git_branch$git_status$python $time$character"""

[directory]
style = "bold #7aa2f7"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "bold #bb9af7"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold #f7768e"
format = "[$all_status$ahead_behind]($style) "

[python]
symbol = " "
style = "bold #9ece6a"
format = "[$symbol$version]($style) "

[time]
disabled = false
style = "bold #a9b1d6"
format = "[$time]($style) "
time_format = "%H:%M"

[character]
success_symbol = "[❯](#7aa2f7)"
error_symbol = "[❯](#f7768e)"
